"""empty message

Revision ID: da2b2b082289
Revises: 84b8d5005f9d
Create Date: 2020-09-06 17:03:01.577535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2b2b082289'
down_revision = '84b8d5005f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
